api:
  services:
    - service: calibrate_co2_value
      variables:
        co2_ppm: int
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda "return co2_ppm;"
            id: scd40

i2c:
  - id: bus_b
    sda: 26
    scl: 27
    scan: true

sensor:
  - platform: scd4x
    i2c_id: bus_b
    id: scd40
    ambient_pressure_compensation_source: indoor_pressure
    temperature_offset: 12.5
    update_interval: 30s
    measurement_mode: low_power_periodic    
    co2:
      name: "CO2"
      id: "co2"
    temperature:
      name: "Temperature"
      id: "temperature"
      filters:
        - lambda: return x - id(scd40_temperature_offset).state;
    humidity:
      name: "Humidity"
      id: "humidity"
      filters:
        - lambda: return x - id(scd40_humidity_offset).state;
    automatic_self_calibration: false

button:
    - platform: template
      name: "Calibrate CO2"
      id: calibrate_scd40
      on_press:
        - scd4x.perform_forced_calibration:
            value: 419
            id: scd40

number:
  - platform: template
    name: SCD40 Temperature Offset
    id: scd40_temperature_offset
    initial_value: 0
    min_value: -70.0
    max_value: 70.0
    entity_category: "CONFIG"
    unit_of_measurement: "°C"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
  - platform: template
    name: SCD40 Humidity Offset
    id: scd40_humidity_offset
    restore_value: true
    initial_value: 0
    min_value: -70.0
    max_value: 70.0
    entity_category: "CONFIG"
    unit_of_measurement: "%"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
